/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import SistemaUniversitario.Disciplina;
import SistemaUniversitario.Excecoes;
import SistemaUniversitario.Turma;
import SistemaUniversitario.TurmaGraduacao;
import static Telas.TelaPrincipal.listaBDDisciplina;
import static Telas.TelaPrincipal.listaBDTurma;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maquina 8
 */
public class cadastrardisciplina extends javax.swing.JInternalFrame {
    public DefaultListModel listModelTotalTurmas = new DefaultListModel();
    public DefaultListModel listModelTurmasSelecionadas = new DefaultListModel();
    public ArrayList<Turma> listaTurmaTemp = new ArrayList<Turma>();
    
    /**
     * Creates new form cadastrardisciplina
     */
    public cadastrardisciplina() {
        initComponents();
        preencheJListTotalTurmas();
        preencheJlistTurmasSelecionadas();
        jListTurmasSelecionadas.setModel(listModelTurmasSelecionadas);
        jListTotalTurmas.setModel(listModelTotalTurmas);
    }

    
    public void preencheJListTotalTurmas(){
        String formatarJList = new String();  
        for (Turma t: listaBDTurma){
            if (t instanceof TurmaGraduacao){
                formatarJList = t.getCodigo() + " - " + t.getProfessor();
                listModelTotalTurmas.addElement(formatarJList);
            }
        }
    }
    
    public void preencheJlistTurmasSelecionadas(){
        listModelTurmasSelecionadas.clear();
        String formatarJList = new String();  
        for (Turma t: listaTurmaTemp){
            if (t instanceof TurmaGraduacao){
                formatarJList = t.getCodigo() + " - " + t.getProfessor();
                listModelTurmasSelecionadas.addElement(formatarJList);
            }
        }
    }
   
    
    public void setPosicao (){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
        
    }
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCargaH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQtdCred = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTotalTurmas = new javax.swing.JList();
        jButtonInsert = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTurmasSelecionadas = new javax.swing.JList();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldQtdMinCred = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setClosable(true);
        setTitle("Cadastrar Disciplina");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Carga Horária: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Qtd. de Créditos: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Qtd. min. de Créditos: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turmas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jListTotalTurmas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListTotalTurmas.setToolTipText("");
        jScrollPane1.setViewportView(jListTotalTurmas);

        jButtonInsert.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonInsert.setText(">>");
        jButtonInsert.setAlignmentY(0.0F);
        jButtonInsert.setBorder(null);
        jButtonInsert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert.setMargin(null);
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jListTurmasSelecionadas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListTurmasSelecionadas.setToolTipText("");
        jScrollPane2.setViewportView(jListTurmasSelecionadas);

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonDelete.setText("<<");
        jButtonDelete.setAlignmentY(0.0F);
        jButtonDelete.setBorder(null);
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete.setMargin(null);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldQtdCred, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldQtdMinCred, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCargaH))
                            .addComponent(jTextFieldNome))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCargaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldQtdCred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQtdMinCred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButton2.setText("Pesquisar");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButton2)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        jTextFieldCargaH.setText(null);
        jTextFieldCod.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldQtdCred.setText(null);
        jTextFieldQtdMinCred.setText(null);
        
        listaTurmaTemp.clear();
        //listModelTurmasSelecionadas.clear();
        preencheJlistTurmasSelecionadas();
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        if (jListTotalTurmas.getSelectedIndex() == -1){
            return;
        }

        for (Turma temp: listaTurmaTemp){
            if (listaBDTurma.get(jListTotalTurmas.getSelectedIndex()).equals(temp)){
                return;
            }
        }
            
        listaTurmaTemp.add(listaBDTurma.get(jListTotalTurmas.getSelectedIndex()));
        preencheJlistTurmasSelecionadas();

    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (jListTurmasSelecionadas.getSelectedIndex() == -1){
            return;
        }

        int x = jListTurmasSelecionadas.getSelectedIndex();
        listaTurmaTemp.remove(x);
        listModelTurmasSelecionadas.remove(x);
        jListTurmasSelecionadas.setModel(listModelTurmasSelecionadas);    
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       
        
        
        
        try{
            if (jTextFieldNome.getText().isEmpty()){
                throw new Excecoes (5001, "Campo nome obrigatório");
            }  
            if (jTextFieldCod.getText().isEmpty()){
                throw new Excecoes (5002, "Campo código obrigatório");
            }
            if (jTextFieldCargaH.getText().isEmpty()){
                throw new Excecoes (5003, "Campo carga horária obrigatório");
            } 
            if (jTextFieldQtdCred.getText().isEmpty()){
                throw new Excecoes (5004, "Campo quantidade de crédito obrigatório");
            }  
            if (jTextFieldQtdMinCred.getText().isEmpty()){
                throw new Excecoes (5005, "Campo quantidade de mínima de crédito obrigatório");
            }
            

            int cod = Integer.parseInt(jTextFieldCod.getText());
            int cargaHoraria = Integer.parseInt(jTextFieldCargaH.getText());
            int quantCreditos = Integer.parseInt(jTextFieldQtdCred.getText());
            int quantMinCreditos = Integer.parseInt(jTextFieldQtdMinCred.getText());
            
            
            for (Disciplina d: listaBDDisciplina){
                if (cod < 1){
                    throw new Excecoes (5007, "Código inválido. Somente números inteiros positivos.");
                }
                if (cod == d.getCod()){
                    if (TelaPrincipal.handleOptionPane("Disciplina concorrente", "Os dados serão sobescritos. Tem certeza disso?") == true){
                        d.setNome(jTextFieldNome.getText());
                        d.setCargaHoraria(Integer.parseInt(jTextFieldCargaH.getText()));
                        d.setQuantCreditos(Integer.parseInt(jTextFieldQtdCred.getText()));
                        d.setQuantMinCreditos(Integer.parseInt(jTextFieldQtdMinCred.getText()));
                        
                        d.clearTurma();
                        for(Turma t2: listaTurmaTemp){
                            d.insertTurma((TurmaGraduacao) t2);
                        }
                        
                        
preencheJlistTurmasSelecionadas();
                        
                        JOptionPane.showMessageDialog(this, "Dados alterados com sucesso!");
                        jButtonLimparActionPerformed(evt);
                        return;
                    }else{
                        return;
                    }
                }
                
                    /*if 
(TelaPrincipal.handleOptionPane("Disciplina 
concorrente", "Os dados serão sobescritos. Tem certeza 
disso?") == true){
                    //d.setartodoumndo
                    JOptionPane.showMessageDialog
(this, "Dadaos alterados com sucesso!");
                    jButtonLimparActionPerformed(evt);
                    return;
                    }else{
                    return;
                    }*/
                
            }
            
            
            Disciplina d = new Disciplina(cod, jTextFieldNome.getText(), cargaHoraria, quantCreditos, quantMinCreditos);
            d.insertArrayTurma(listaTurmaTemp);
            listaBDDisciplina.add(d);
            JOptionPane.showMessageDialog(this, "Dados cadastrados com sucesso!");
            jButtonLimparActionPerformed(evt);
            
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Impossivel converter essa letra aí jhowwwww!\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);   
 
        } catch (Excecoes e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        Object[] possibilities = listaBDDisciplina.toArray();
        String s = (String)JOptionPane.showInputDialog(
        this,
        "Complete the sentence:\n"
        + "\"Green eggs and...\"",
        "Customized Dialog",
        JOptionPane.PLAIN_MESSAGE,
        frameIcon,
        possibilities,
        "ham");

        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            //setLabel("Green eggs and... " + s + "!");
            return;
        }

        //If you're here, the return value was null/empty.
        //setLabel("Come on, finish the sentence!");
        
        
        /* try {
        if (jTextFieldMat.getText().isEmpty()){
        throw new Excecoes(9007, "Campo matrícula inválido.");
        }
        int mat = Integer.parseInt(jTextFieldMat.getText());
        if (mat < 0){
        throw new Excecoes(9008, "Matrícula inválida. Somente números inteiros positivos.");
        }
        for (Aluno a: TelaPrincipal.listaBDAluno){
        if (a.getMatricula() == mat){
        if (TelaPrincipal.handleOptionPane("Excluir", "Matrícula " + a.getMatricula()+ " encontrada!\n" +
        "Tem certeza que deseja excluir " + a.getNome() + "?") == true){
        TelaPrincipal.listaBDAluno.remove(a);
        JOptionPane.showMessageDialog(this, "Aluno Excluido com Sucesso");
        jButtonLimparActionPerformed(evt);
        return;
        }else{
        return;
        }
        }
        }
        JOptionPane.showMessageDialog(this, "Nenhum Aluno encontrado");
        jButtonLimparActionPerformed(evt);
        
        } catch (NullPointerException ex){
        JOptionPane.showMessageDialog(this, "Null test.\n" + ex.getMessage());
        } catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Campo Matrícula inválido!\n" + ex.getMessage());
        } catch (Excecoes ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE );
        }*/
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListTotalTurmas;
    private javax.swing.JList jListTurmasSelecionadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldCargaH;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldQtdCred;
    private javax.swing.JTextField jTextFieldQtdMinCred;
    // End of variables declaration//GEN-END:variables
}
